# Generated by Django 2.0 on 2020-06-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200624_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
