# Generated by Django 2.0 on 2020-06-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200624_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video1',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Video1',
        ),
    ]
